/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: vroom.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "pb.h"
void   reply__init
                     (Reply         *message)
{
  static Reply init_value = REPLY__INIT;
  *message = init_value;
}
size_t reply__get_packed_size
                     (const Reply *message)
{
  assert(message->base.descriptor == &reply__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t reply__pack
                     (const Reply *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &reply__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t reply__pack_to_buffer
                     (const Reply *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &reply__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Reply *
       reply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Reply *)
     protobuf_c_message_unpack (&reply__descriptor,
                                allocator, len, data);
}
void   reply__free_unpacked
                     (Reply *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &reply__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   create_scene__init
                     (CreateScene         *message)
{
  static CreateScene init_value = CREATE_SCENE__INIT;
  *message = init_value;
}
size_t create_scene__get_packed_size
                     (const CreateScene *message)
{
  assert(message->base.descriptor == &create_scene__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t create_scene__pack
                     (const CreateScene *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &create_scene__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t create_scene__pack_to_buffer
                     (const CreateScene *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &create_scene__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CreateScene *
       create_scene__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CreateScene *)
     protobuf_c_message_unpack (&create_scene__descriptor,
                                allocator, len, data);
}
void   create_scene__free_unpacked
                     (CreateScene *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &create_scene__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   destroy_scene__init
                     (DestroyScene         *message)
{
  static DestroyScene init_value = DESTROY_SCENE__INIT;
  *message = init_value;
}
size_t destroy_scene__get_packed_size
                     (const DestroyScene *message)
{
  assert(message->base.descriptor == &destroy_scene__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t destroy_scene__pack
                     (const DestroyScene *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &destroy_scene__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t destroy_scene__pack_to_buffer
                     (const DestroyScene *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &destroy_scene__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DestroyScene *
       destroy_scene__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DestroyScene *)
     protobuf_c_message_unpack (&destroy_scene__descriptor,
                                allocator, len, data);
}
void   destroy_scene__free_unpacked
                     (DestroyScene *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &destroy_scene__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   create_memory__init
                     (CreateMemory         *message)
{
  static CreateMemory init_value = CREATE_MEMORY__INIT;
  *message = init_value;
}
size_t create_memory__get_packed_size
                     (const CreateMemory *message)
{
  assert(message->base.descriptor == &create_memory__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t create_memory__pack
                     (const CreateMemory *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &create_memory__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t create_memory__pack_to_buffer
                     (const CreateMemory *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &create_memory__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CreateMemory *
       create_memory__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CreateMemory *)
     protobuf_c_message_unpack (&create_memory__descriptor,
                                allocator, len, data);
}
void   create_memory__free_unpacked
                     (CreateMemory *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &create_memory__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   create_data_object__init
                     (CreateDataObject         *message)
{
  static CreateDataObject init_value = CREATE_DATA_OBJECT__INIT;
  *message = init_value;
}
size_t create_data_object__get_packed_size
                     (const CreateDataObject *message)
{
  assert(message->base.descriptor == &create_data_object__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t create_data_object__pack
                     (const CreateDataObject *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &create_data_object__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t create_data_object__pack_to_buffer
                     (const CreateDataObject *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &create_data_object__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CreateDataObject *
       create_data_object__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CreateDataObject *)
     protobuf_c_message_unpack (&create_data_object__descriptor,
                                allocator, len, data);
}
void   create_data_object__free_unpacked
                     (CreateDataObject *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &create_data_object__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   create_texture_object__init
                     (CreateTextureObject         *message)
{
  static CreateTextureObject init_value = CREATE_TEXTURE_OBJECT__INIT;
  *message = init_value;
}
size_t create_texture_object__get_packed_size
                     (const CreateTextureObject *message)
{
  assert(message->base.descriptor == &create_texture_object__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t create_texture_object__pack
                     (const CreateTextureObject *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &create_texture_object__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t create_texture_object__pack_to_buffer
                     (const CreateTextureObject *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &create_texture_object__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CreateTextureObject *
       create_texture_object__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CreateTextureObject *)
     protobuf_c_message_unpack (&create_texture_object__descriptor,
                                allocator, len, data);
}
void   create_texture_object__free_unpacked
                     (CreateTextureObject *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &create_texture_object__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   run_program__init
                     (RunProgram         *message)
{
  static RunProgram init_value = RUN_PROGRAM__INIT;
  *message = init_value;
}
size_t run_program__get_packed_size
                     (const RunProgram *message)
{
  assert(message->base.descriptor == &run_program__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t run_program__pack
                     (const RunProgram *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &run_program__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t run_program__pack_to_buffer
                     (const RunProgram *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &run_program__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RunProgram *
       run_program__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RunProgram *)
     protobuf_c_message_unpack (&run_program__descriptor,
                                allocator, len, data);
}
void   run_program__free_unpacked
                     (RunProgram *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &run_program__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   set_skybox__init
                     (SetSkybox         *message)
{
  static SetSkybox init_value = SET_SKYBOX__INIT;
  *message = init_value;
}
size_t set_skybox__get_packed_size
                     (const SetSkybox *message)
{
  assert(message->base.descriptor == &set_skybox__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t set_skybox__pack
                     (const SetSkybox *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &set_skybox__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t set_skybox__pack_to_buffer
                     (const SetSkybox *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &set_skybox__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SetSkybox *
       set_skybox__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SetSkybox *)
     protobuf_c_message_unpack (&set_skybox__descriptor,
                                allocator, len, data);
}
void   set_skybox__free_unpacked
                     (SetSkybox *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &set_skybox__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   update_system_matrix__init
                     (UpdateSystemMatrix         *message)
{
  static UpdateSystemMatrix init_value = UPDATE_SYSTEM_MATRIX__INIT;
  *message = init_value;
}
size_t update_system_matrix__get_packed_size
                     (const UpdateSystemMatrix *message)
{
  assert(message->base.descriptor == &update_system_matrix__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t update_system_matrix__pack
                     (const UpdateSystemMatrix *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &update_system_matrix__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t update_system_matrix__pack_to_buffer
                     (const UpdateSystemMatrix *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &update_system_matrix__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UpdateSystemMatrix *
       update_system_matrix__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UpdateSystemMatrix *)
     protobuf_c_message_unpack (&update_system_matrix__descriptor,
                                allocator, len, data);
}
void   update_system_matrix__free_unpacked
                     (UpdateSystemMatrix *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &update_system_matrix__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   destroy_object__init
                     (DestroyObject         *message)
{
  static DestroyObject init_value = DESTROY_OBJECT__INIT;
  *message = init_value;
}
size_t destroy_object__get_packed_size
                     (const DestroyObject *message)
{
  assert(message->base.descriptor == &destroy_object__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t destroy_object__pack
                     (const DestroyObject *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &destroy_object__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t destroy_object__pack_to_buffer
                     (const DestroyObject *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &destroy_object__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DestroyObject *
       destroy_object__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DestroyObject *)
     protobuf_c_message_unpack (&destroy_object__descriptor,
                                allocator, len, data);
}
void   destroy_object__free_unpacked
                     (DestroyObject *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &destroy_object__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor reply__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Reply, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error_code",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Reply, error_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned reply__field_indices_by_name[] = {
  1,   /* field[1] = error_code */
  0,   /* field[0] = id */
};
static const ProtobufCIntRange reply__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor reply__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Reply",
  "Reply",
  "Reply",
  "",
  sizeof(Reply),
  2,
  reply__field_descriptors,
  reply__field_indices_by_name,
  1,  reply__number_ranges,
  (ProtobufCMessageInit) reply__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor create_scene__field_descriptors[1] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CreateScene, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned create_scene__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange create_scene__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor create_scene__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CreateScene",
  "CreateScene",
  "CreateScene",
  "",
  sizeof(CreateScene),
  1,
  create_scene__field_descriptors,
  create_scene__field_indices_by_name,
  1,  create_scene__number_ranges,
  (ProtobufCMessageInit) create_scene__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor destroy_scene__field_descriptors[1] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DestroyScene, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned destroy_scene__field_indices_by_name[] = {
  0,   /* field[0] = id */
};
static const ProtobufCIntRange destroy_scene__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor destroy_scene__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DestroyScene",
  "DestroyScene",
  "DestroyScene",
  "",
  sizeof(DestroyScene),
  1,
  destroy_scene__field_descriptors,
  destroy_scene__field_indices_by_name,
  1,  destroy_scene__number_ranges,
  (ProtobufCMessageInit) destroy_scene__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor create_memory__field_descriptors[2] =
{
  {
    "scene_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateMemory, scene_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateMemory, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned create_memory__field_indices_by_name[] = {
  0,   /* field[0] = scene_id */
  1,   /* field[1] = size */
};
static const ProtobufCIntRange create_memory__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor create_memory__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CreateMemory",
  "CreateMemory",
  "CreateMemory",
  "",
  sizeof(CreateMemory),
  2,
  create_memory__field_descriptors,
  create_memory__field_indices_by_name,
  1,  create_memory__number_ranges,
  (ProtobufCMessageInit) create_memory__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue create_data_object__type__enum_values_by_number[9] =
{
  { "VERTEX", "CREATE_DATA_OBJECT__TYPE__VERTEX", 0 },
  { "NORMAL", "CREATE_DATA_OBJECT__TYPE__NORMAL", 1 },
  { "INDEX", "CREATE_DATA_OBJECT__TYPE__INDEX", 2 },
  { "COLOR", "CREATE_DATA_OBJECT__TYPE__COLOR", 3 },
  { "UV", "CREATE_DATA_OBJECT__TYPE__UV", 4 },
  { "TEXTURE", "CREATE_DATA_OBJECT__TYPE__TEXTURE", 5 },
  { "MATRIX", "CREATE_DATA_OBJECT__TYPE__MATRIX", 6 },
  { "PROGRAM", "CREATE_DATA_OBJECT__TYPE__PROGRAM", 7 },
  { "REGISTER", "CREATE_DATA_OBJECT__TYPE__REGISTER", 8 },
};
static const ProtobufCIntRange create_data_object__type__value_ranges[] = {
{0, 0},{0, 9}
};
static const ProtobufCEnumValueIndex create_data_object__type__enum_values_by_name[9] =
{
  { "COLOR", 3 },
  { "INDEX", 2 },
  { "MATRIX", 6 },
  { "NORMAL", 1 },
  { "PROGRAM", 7 },
  { "REGISTER", 8 },
  { "TEXTURE", 5 },
  { "UV", 4 },
  { "VERTEX", 0 },
};
const ProtobufCEnumDescriptor create_data_object__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "CreateDataObject.Type",
  "Type",
  "CreateDataObject__Type",
  "",
  9,
  create_data_object__type__enum_values_by_number,
  9,
  create_data_object__type__enum_values_by_name,
  1,
  create_data_object__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor create_data_object__field_descriptors[7] =
{
  {
    "scene_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateDataObject, scene_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "memory_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateDataObject, memory_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "memory_offset",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateDataObject, memory_offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "memory_length",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateDataObject, memory_length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "item_length",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateDataObject, item_length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data_length",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateDataObject, data_length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(CreateDataObject, type),
    &create_data_object__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned create_data_object__field_indices_by_name[] = {
  5,   /* field[5] = data_length */
  4,   /* field[4] = item_length */
  1,   /* field[1] = memory_id */
  3,   /* field[3] = memory_length */
  2,   /* field[2] = memory_offset */
  0,   /* field[0] = scene_id */
  6,   /* field[6] = type */
};
static const ProtobufCIntRange create_data_object__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor create_data_object__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CreateDataObject",
  "CreateDataObject",
  "CreateDataObject",
  "",
  sizeof(CreateDataObject),
  7,
  create_data_object__field_descriptors,
  create_data_object__field_indices_by_name,
  1,  create_data_object__number_ranges,
  (ProtobufCMessageInit) create_data_object__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue create_texture_object__format__enum_values_by_number[6] =
{
  { "BGR888", "CREATE_TEXTURE_OBJECT__FORMAT__BGR888", 0 },
  { "XBGR8888", "CREATE_TEXTURE_OBJECT__FORMAT__XBGR8888", 1 },
  { "ABGR8888", "CREATE_TEXTURE_OBJECT__FORMAT__ABGR8888", 2 },
  { "RGB888", "CREATE_TEXTURE_OBJECT__FORMAT__RGB888", 3 },
  { "XRGB8888", "CREATE_TEXTURE_OBJECT__FORMAT__XRGB8888", 4 },
  { "ARGB8888", "CREATE_TEXTURE_OBJECT__FORMAT__ARGB8888", 5 },
};
static const ProtobufCIntRange create_texture_object__format__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex create_texture_object__format__enum_values_by_name[6] =
{
  { "ABGR8888", 2 },
  { "ARGB8888", 5 },
  { "BGR888", 0 },
  { "RGB888", 3 },
  { "XBGR8888", 1 },
  { "XRGB8888", 4 },
};
const ProtobufCEnumDescriptor create_texture_object__format__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "CreateTextureObject.Format",
  "Format",
  "CreateTextureObject__Format",
  "",
  6,
  create_texture_object__format__enum_values_by_number,
  6,
  create_texture_object__format__enum_values_by_name,
  1,
  create_texture_object__format__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue create_texture_object__type__enum_values_by_number[2] =
{
  { "TEXTURE_2D", "CREATE_TEXTURE_OBJECT__TYPE__TEXTURE_2D", 0 },
  { "TEXTURE_CUBE_MAP", "CREATE_TEXTURE_OBJECT__TYPE__TEXTURE_CUBE_MAP", 1 },
};
static const ProtobufCIntRange create_texture_object__type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex create_texture_object__type__enum_values_by_name[2] =
{
  { "TEXTURE_2D", 0 },
  { "TEXTURE_CUBE_MAP", 1 },
};
const ProtobufCEnumDescriptor create_texture_object__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "CreateTextureObject.Type",
  "Type",
  "CreateTextureObject__Type",
  "",
  2,
  create_texture_object__type__enum_values_by_number,
  2,
  create_texture_object__type__enum_values_by_name,
  1,
  create_texture_object__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor create_texture_object__field_descriptors[6] =
{
  {
    "scene_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateTextureObject, scene_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateTextureObject, data_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "width",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateTextureObject, width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "height",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateTextureObject, height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "format",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(CreateTextureObject, format),
    &create_texture_object__format__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(CreateTextureObject, type),
    &create_texture_object__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned create_texture_object__field_indices_by_name[] = {
  1,   /* field[1] = data_id */
  4,   /* field[4] = format */
  3,   /* field[3] = height */
  0,   /* field[0] = scene_id */
  5,   /* field[5] = type */
  2,   /* field[2] = width */
};
static const ProtobufCIntRange create_texture_object__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor create_texture_object__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CreateTextureObject",
  "CreateTextureObject",
  "CreateTextureObject",
  "",
  sizeof(CreateTextureObject),
  6,
  create_texture_object__field_descriptors,
  create_texture_object__field_indices_by_name,
  1,  create_texture_object__number_ranges,
  (ProtobufCMessageInit) create_texture_object__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor run_program__field_descriptors[3] =
{
  {
    "scene_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RunProgram, scene_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "program_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RunProgram, program_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "register_id",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(RunProgram, register_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned run_program__field_indices_by_name[] = {
  1,   /* field[1] = program_id */
  2,   /* field[2] = register_id */
  0,   /* field[0] = scene_id */
};
static const ProtobufCIntRange run_program__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor run_program__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RunProgram",
  "RunProgram",
  "RunProgram",
  "",
  sizeof(RunProgram),
  3,
  run_program__field_descriptors,
  run_program__field_indices_by_name,
  1,  run_program__number_ranges,
  (ProtobufCMessageInit) run_program__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor set_skybox__field_descriptors[2] =
{
  {
    "scene_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SetSkybox, scene_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "texture_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SetSkybox, texture_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned set_skybox__field_indices_by_name[] = {
  0,   /* field[0] = scene_id */
  1,   /* field[1] = texture_id */
};
static const ProtobufCIntRange set_skybox__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor set_skybox__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SetSkybox",
  "SetSkybox",
  "SetSkybox",
  "",
  sizeof(SetSkybox),
  2,
  set_skybox__field_descriptors,
  set_skybox__field_indices_by_name,
  1,  set_skybox__number_ranges,
  (ProtobufCMessageInit) set_skybox__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue update_system_matrix__matrix_type__enum_values_by_number[2] =
{
  { "HEAD", "UPDATE_SYSTEM_MATRIX__MATRIX_TYPE__HEAD", 0 },
  { "BODY", "UPDATE_SYSTEM_MATRIX__MATRIX_TYPE__BODY", 1 },
};
static const ProtobufCIntRange update_system_matrix__matrix_type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex update_system_matrix__matrix_type__enum_values_by_name[2] =
{
  { "BODY", 1 },
  { "HEAD", 0 },
};
const ProtobufCEnumDescriptor update_system_matrix__matrix_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "UpdateSystemMatrix.MatrixType",
  "MatrixType",
  "UpdateSystemMatrix__MatrixType",
  "",
  2,
  update_system_matrix__matrix_type__enum_values_by_number,
  2,
  update_system_matrix__matrix_type__enum_values_by_name,
  1,
  update_system_matrix__matrix_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue update_system_matrix__update_type__enum_values_by_number[2] =
{
  { "MULTIPLY", "UPDATE_SYSTEM_MATRIX__UPDATE_TYPE__MULTIPLY", 0 },
  { "SET", "UPDATE_SYSTEM_MATRIX__UPDATE_TYPE__SET", 1 },
};
static const ProtobufCIntRange update_system_matrix__update_type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex update_system_matrix__update_type__enum_values_by_name[2] =
{
  { "MULTIPLY", 0 },
  { "SET", 1 },
};
const ProtobufCEnumDescriptor update_system_matrix__update_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "UpdateSystemMatrix.UpdateType",
  "UpdateType",
  "UpdateSystemMatrix__UpdateType",
  "",
  2,
  update_system_matrix__update_type__enum_values_by_number,
  2,
  update_system_matrix__update_type__enum_values_by_name,
  1,
  update_system_matrix__update_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor update_system_matrix__field_descriptors[5] =
{
  {
    "scene_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(UpdateSystemMatrix, scene_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(UpdateSystemMatrix, data_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data_index",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(UpdateSystemMatrix, data_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "matrix_type",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(UpdateSystemMatrix, matrix_type),
    &update_system_matrix__matrix_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "update_type",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(UpdateSystemMatrix, update_type),
    &update_system_matrix__update_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned update_system_matrix__field_indices_by_name[] = {
  1,   /* field[1] = data_id */
  2,   /* field[2] = data_index */
  3,   /* field[3] = matrix_type */
  0,   /* field[0] = scene_id */
  4,   /* field[4] = update_type */
};
static const ProtobufCIntRange update_system_matrix__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor update_system_matrix__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "UpdateSystemMatrix",
  "UpdateSystemMatrix",
  "UpdateSystemMatrix",
  "",
  sizeof(UpdateSystemMatrix),
  5,
  update_system_matrix__field_descriptors,
  update_system_matrix__field_indices_by_name,
  1,  update_system_matrix__number_ranges,
  (ProtobufCMessageInit) update_system_matrix__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor destroy_object__field_descriptors[2] =
{
  {
    "scene_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DestroyObject, scene_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DestroyObject, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned destroy_object__field_indices_by_name[] = {
  1,   /* field[1] = id */
  0,   /* field[0] = scene_id */
};
static const ProtobufCIntRange destroy_object__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor destroy_object__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DestroyObject",
  "DestroyObject",
  "DestroyObject",
  "",
  sizeof(DestroyObject),
  2,
  destroy_object__field_descriptors,
  destroy_object__field_indices_by_name,
  1,  destroy_object__number_ranges,
  (ProtobufCMessageInit) destroy_object__init,
  NULL,NULL,NULL    /* reserved[123] */
};
