/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: vroom.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "vroom.pb-c.h"
void   reply__init
                     (Reply         *message)
{
  static Reply init_value = REPLY__INIT;
  *message = init_value;
}
size_t reply__get_packed_size
                     (const Reply *message)
{
  assert(message->base.descriptor == &reply__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t reply__pack
                     (const Reply *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &reply__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t reply__pack_to_buffer
                     (const Reply *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &reply__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Reply *
       reply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Reply *)
     protobuf_c_message_unpack (&reply__descriptor,
                                allocator, len, data);
}
void   reply__free_unpacked
                     (Reply *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &reply__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   create_scene__init
                     (CreateScene         *message)
{
  static CreateScene init_value = CREATE_SCENE__INIT;
  *message = init_value;
}
size_t create_scene__get_packed_size
                     (const CreateScene *message)
{
  assert(message->base.descriptor == &create_scene__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t create_scene__pack
                     (const CreateScene *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &create_scene__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t create_scene__pack_to_buffer
                     (const CreateScene *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &create_scene__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CreateScene *
       create_scene__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CreateScene *)
     protobuf_c_message_unpack (&create_scene__descriptor,
                                allocator, len, data);
}
void   create_scene__free_unpacked
                     (CreateScene *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &create_scene__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   destroy_scene__init
                     (DestroyScene         *message)
{
  static DestroyScene init_value = DESTROY_SCENE__INIT;
  *message = init_value;
}
size_t destroy_scene__get_packed_size
                     (const DestroyScene *message)
{
  assert(message->base.descriptor == &destroy_scene__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t destroy_scene__pack
                     (const DestroyScene *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &destroy_scene__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t destroy_scene__pack_to_buffer
                     (const DestroyScene *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &destroy_scene__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DestroyScene *
       destroy_scene__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DestroyScene *)
     protobuf_c_message_unpack (&destroy_scene__descriptor,
                                allocator, len, data);
}
void   destroy_scene__free_unpacked
                     (DestroyScene *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &destroy_scene__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   create_data_object__init
                     (CreateDataObject         *message)
{
  static CreateDataObject init_value = CREATE_DATA_OBJECT__INIT;
  *message = init_value;
}
size_t create_data_object__get_packed_size
                     (const CreateDataObject *message)
{
  assert(message->base.descriptor == &create_data_object__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t create_data_object__pack
                     (const CreateDataObject *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &create_data_object__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t create_data_object__pack_to_buffer
                     (const CreateDataObject *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &create_data_object__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CreateDataObject *
       create_data_object__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CreateDataObject *)
     protobuf_c_message_unpack (&create_data_object__descriptor,
                                allocator, len, data);
}
void   create_data_object__free_unpacked
                     (CreateDataObject *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &create_data_object__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   destroy_data_object__init
                     (DestroyDataObject         *message)
{
  static DestroyDataObject init_value = DESTROY_DATA_OBJECT__INIT;
  *message = init_value;
}
size_t destroy_data_object__get_packed_size
                     (const DestroyDataObject *message)
{
  assert(message->base.descriptor == &destroy_data_object__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t destroy_data_object__pack
                     (const DestroyDataObject *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &destroy_data_object__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t destroy_data_object__pack_to_buffer
                     (const DestroyDataObject *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &destroy_data_object__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DestroyDataObject *
       destroy_data_object__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DestroyDataObject *)
     protobuf_c_message_unpack (&destroy_data_object__descriptor,
                                allocator, len, data);
}
void   destroy_data_object__free_unpacked
                     (DestroyDataObject *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &destroy_data_object__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   create_geometry_object__init
                     (CreateGeometryObject         *message)
{
  static CreateGeometryObject init_value = CREATE_GEOMETRY_OBJECT__INIT;
  *message = init_value;
}
size_t create_geometry_object__get_packed_size
                     (const CreateGeometryObject *message)
{
  assert(message->base.descriptor == &create_geometry_object__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t create_geometry_object__pack
                     (const CreateGeometryObject *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &create_geometry_object__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t create_geometry_object__pack_to_buffer
                     (const CreateGeometryObject *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &create_geometry_object__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CreateGeometryObject *
       create_geometry_object__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CreateGeometryObject *)
     protobuf_c_message_unpack (&create_geometry_object__descriptor,
                                allocator, len, data);
}
void   create_geometry_object__free_unpacked
                     (CreateGeometryObject *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &create_geometry_object__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   create_color_mesh__init
                     (CreateColorMesh         *message)
{
  static CreateColorMesh init_value = CREATE_COLOR_MESH__INIT;
  *message = init_value;
}
size_t create_color_mesh__get_packed_size
                     (const CreateColorMesh *message)
{
  assert(message->base.descriptor == &create_color_mesh__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t create_color_mesh__pack
                     (const CreateColorMesh *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &create_color_mesh__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t create_color_mesh__pack_to_buffer
                     (const CreateColorMesh *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &create_color_mesh__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CreateColorMesh *
       create_color_mesh__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CreateColorMesh *)
     protobuf_c_message_unpack (&create_color_mesh__descriptor,
                                allocator, len, data);
}
void   create_color_mesh__free_unpacked
                     (CreateColorMesh *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &create_color_mesh__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   create_texture_mesh__init
                     (CreateTextureMesh         *message)
{
  static CreateTextureMesh init_value = CREATE_TEXTURE_MESH__INIT;
  *message = init_value;
}
size_t create_texture_mesh__get_packed_size
                     (const CreateTextureMesh *message)
{
  assert(message->base.descriptor == &create_texture_mesh__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t create_texture_mesh__pack
                     (const CreateTextureMesh *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &create_texture_mesh__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t create_texture_mesh__pack_to_buffer
                     (const CreateTextureMesh *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &create_texture_mesh__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CreateTextureMesh *
       create_texture_mesh__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CreateTextureMesh *)
     protobuf_c_message_unpack (&create_texture_mesh__descriptor,
                                allocator, len, data);
}
void   create_texture_mesh__free_unpacked
                     (CreateTextureMesh *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &create_texture_mesh__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor reply__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Reply, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error_code",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Reply, error_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned reply__field_indices_by_name[] = {
  1,   /* field[1] = error_code */
  0,   /* field[0] = id */
};
static const ProtobufCIntRange reply__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor reply__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Reply",
  "Reply",
  "Reply",
  "",
  sizeof(Reply),
  2,
  reply__field_descriptors,
  reply__field_indices_by_name,
  1,  reply__number_ranges,
  (ProtobufCMessageInit) reply__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor create_scene__field_descriptors[1] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CreateScene, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned create_scene__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange create_scene__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor create_scene__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CreateScene",
  "CreateScene",
  "CreateScene",
  "",
  sizeof(CreateScene),
  1,
  create_scene__field_descriptors,
  create_scene__field_indices_by_name,
  1,  create_scene__number_ranges,
  (ProtobufCMessageInit) create_scene__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor destroy_scene__field_descriptors[1] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DestroyScene, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned destroy_scene__field_indices_by_name[] = {
  0,   /* field[0] = id */
};
static const ProtobufCIntRange destroy_scene__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor destroy_scene__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DestroyScene",
  "DestroyScene",
  "DestroyScene",
  "",
  sizeof(DestroyScene),
  1,
  destroy_scene__field_descriptors,
  destroy_scene__field_indices_by_name,
  1,  destroy_scene__number_ranges,
  (ProtobufCMessageInit) destroy_scene__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue create_data_object__type__enum_values_by_number[6] =
{
  { "UV", "CREATE_DATA_OBJECT__TYPE__UV", 0 },
  { "COLOR", "CREATE_DATA_OBJECT__TYPE__COLOR", 1 },
  { "TEXTURE", "CREATE_DATA_OBJECT__TYPE__TEXTURE", 2 },
  { "VERTEX", "CREATE_DATA_OBJECT__TYPE__VERTEX", 3 },
  { "NORMAL", "CREATE_DATA_OBJECT__TYPE__NORMAL", 4 },
  { "INDEX", "CREATE_DATA_OBJECT__TYPE__INDEX", 5 },
};
static const ProtobufCIntRange create_data_object__type__value_ranges[] = {
{0, 0},{0, 6}
};
const ProtobufCEnumValueIndex create_data_object__type__enum_values_by_name[6] =
{
  { "COLOR", 1 },
  { "INDEX", 5 },
  { "NORMAL", 4 },
  { "TEXTURE", 2 },
  { "UV", 0 },
  { "VERTEX", 3 },
};
const ProtobufCEnumDescriptor create_data_object__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "CreateDataObject.Type",
  "Type",
  "CreateDataObject__Type",
  "",
  6,
  create_data_object__type__enum_values_by_number,
  6,
  create_data_object__type__enum_values_by_name,
  1,
  create_data_object__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor create_data_object__field_descriptors[6] =
{
  {
    "scene_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateDataObject, scene_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(CreateDataObject, type),
    &create_data_object__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "shm_fd",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateDataObject, shm_fd),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "offset",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateDataObject, offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size_of",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateDataObject, size_of),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stride",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateDataObject, stride),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned create_data_object__field_indices_by_name[] = {
  3,   /* field[3] = offset */
  0,   /* field[0] = scene_id */
  2,   /* field[2] = shm_fd */
  4,   /* field[4] = size_of */
  5,   /* field[5] = stride */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange create_data_object__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor create_data_object__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CreateDataObject",
  "CreateDataObject",
  "CreateDataObject",
  "",
  sizeof(CreateDataObject),
  6,
  create_data_object__field_descriptors,
  create_data_object__field_indices_by_name,
  1,  create_data_object__number_ranges,
  (ProtobufCMessageInit) create_data_object__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor destroy_data_object__field_descriptors[2] =
{
  {
    "scene_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DestroyDataObject, scene_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DestroyDataObject, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned destroy_data_object__field_indices_by_name[] = {
  1,   /* field[1] = id */
  0,   /* field[0] = scene_id */
};
static const ProtobufCIntRange destroy_data_object__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor destroy_data_object__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DestroyDataObject",
  "DestroyDataObject",
  "DestroyDataObject",
  "",
  sizeof(DestroyDataObject),
  2,
  destroy_data_object__field_descriptors,
  destroy_data_object__field_indices_by_name,
  1,  destroy_data_object__number_ranges,
  (ProtobufCMessageInit) destroy_data_object__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor create_geometry_object__field_descriptors[4] =
{
  {
    "scene_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateGeometryObject, scene_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vertex_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateGeometryObject, vertex_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "normal_id",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateGeometryObject, normal_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "index_id",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateGeometryObject, index_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned create_geometry_object__field_indices_by_name[] = {
  3,   /* field[3] = index_id */
  2,   /* field[2] = normal_id */
  0,   /* field[0] = scene_id */
  1,   /* field[1] = vertex_id */
};
static const ProtobufCIntRange create_geometry_object__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor create_geometry_object__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CreateGeometryObject",
  "CreateGeometryObject",
  "CreateGeometryObject",
  "",
  sizeof(CreateGeometryObject),
  4,
  create_geometry_object__field_descriptors,
  create_geometry_object__field_indices_by_name,
  1,  create_geometry_object__number_ranges,
  (ProtobufCMessageInit) create_geometry_object__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor create_color_mesh__field_descriptors[6] =
{
  {
    "scene_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateColorMesh, scene_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "geometry_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateColorMesh, geometry_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(CreateColorMesh, r),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "g",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(CreateColorMesh, g),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "b",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(CreateColorMesh, b),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "a",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(CreateColorMesh, a),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned create_color_mesh__field_indices_by_name[] = {
  5,   /* field[5] = a */
  4,   /* field[4] = b */
  3,   /* field[3] = g */
  1,   /* field[1] = geometry_id */
  2,   /* field[2] = r */
  0,   /* field[0] = scene_id */
};
static const ProtobufCIntRange create_color_mesh__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor create_color_mesh__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CreateColorMesh",
  "CreateColorMesh",
  "CreateColorMesh",
  "",
  sizeof(CreateColorMesh),
  6,
  create_color_mesh__field_descriptors,
  create_color_mesh__field_indices_by_name,
  1,  create_color_mesh__number_ranges,
  (ProtobufCMessageInit) create_color_mesh__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor create_texture_mesh__field_descriptors[4] =
{
  {
    "scene_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateTextureMesh, scene_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "geometry_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateTextureMesh, geometry_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uv_id",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateTextureMesh, uv_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "texture_id",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateTextureMesh, texture_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned create_texture_mesh__field_indices_by_name[] = {
  1,   /* field[1] = geometry_id */
  0,   /* field[0] = scene_id */
  3,   /* field[3] = texture_id */
  2,   /* field[2] = uv_id */
};
static const ProtobufCIntRange create_texture_mesh__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor create_texture_mesh__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CreateTextureMesh",
  "CreateTextureMesh",
  "CreateTextureMesh",
  "",
  sizeof(CreateTextureMesh),
  4,
  create_texture_mesh__field_descriptors,
  create_texture_mesh__field_indices_by_name,
  1,  create_texture_mesh__number_ranges,
  (ProtobufCMessageInit) create_texture_mesh__init,
  NULL,NULL,NULL    /* reserved[123] */
};
