/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: vroom.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "vroom_pb.h"
void   reply__init
                     (Reply         *message)
{
  static Reply init_value = REPLY__INIT;
  *message = init_value;
}
size_t reply__get_packed_size
                     (const Reply *message)
{
  assert(message->base.descriptor == &reply__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t reply__pack
                     (const Reply *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &reply__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t reply__pack_to_buffer
                     (const Reply *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &reply__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Reply *
       reply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Reply *)
     protobuf_c_message_unpack (&reply__descriptor,
                                allocator, len, data);
}
void   reply__free_unpacked
                     (Reply *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &reply__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   create_scene__init
                     (CreateScene         *message)
{
  static CreateScene init_value = CREATE_SCENE__INIT;
  *message = init_value;
}
size_t create_scene__get_packed_size
                     (const CreateScene *message)
{
  assert(message->base.descriptor == &create_scene__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t create_scene__pack
                     (const CreateScene *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &create_scene__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t create_scene__pack_to_buffer
                     (const CreateScene *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &create_scene__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CreateScene *
       create_scene__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CreateScene *)
     protobuf_c_message_unpack (&create_scene__descriptor,
                                allocator, len, data);
}
void   create_scene__free_unpacked
                     (CreateScene *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &create_scene__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   destroy_scene__init
                     (DestroyScene         *message)
{
  static DestroyScene init_value = DESTROY_SCENE__INIT;
  *message = init_value;
}
size_t destroy_scene__get_packed_size
                     (const DestroyScene *message)
{
  assert(message->base.descriptor == &destroy_scene__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t destroy_scene__pack
                     (const DestroyScene *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &destroy_scene__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t destroy_scene__pack_to_buffer
                     (const DestroyScene *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &destroy_scene__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DestroyScene *
       destroy_scene__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DestroyScene *)
     protobuf_c_message_unpack (&destroy_scene__descriptor,
                                allocator, len, data);
}
void   destroy_scene__free_unpacked
                     (DestroyScene *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &destroy_scene__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   create_memory__init
                     (CreateMemory         *message)
{
  static CreateMemory init_value = CREATE_MEMORY__INIT;
  *message = init_value;
}
size_t create_memory__get_packed_size
                     (const CreateMemory *message)
{
  assert(message->base.descriptor == &create_memory__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t create_memory__pack
                     (const CreateMemory *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &create_memory__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t create_memory__pack_to_buffer
                     (const CreateMemory *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &create_memory__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CreateMemory *
       create_memory__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CreateMemory *)
     protobuf_c_message_unpack (&create_memory__descriptor,
                                allocator, len, data);
}
void   create_memory__free_unpacked
                     (CreateMemory *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &create_memory__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   create_data_object__init
                     (CreateDataObject         *message)
{
  static CreateDataObject init_value = CREATE_DATA_OBJECT__INIT;
  *message = init_value;
}
size_t create_data_object__get_packed_size
                     (const CreateDataObject *message)
{
  assert(message->base.descriptor == &create_data_object__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t create_data_object__pack
                     (const CreateDataObject *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &create_data_object__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t create_data_object__pack_to_buffer
                     (const CreateDataObject *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &create_data_object__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CreateDataObject *
       create_data_object__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CreateDataObject *)
     protobuf_c_message_unpack (&create_data_object__descriptor,
                                allocator, len, data);
}
void   create_data_object__free_unpacked
                     (CreateDataObject *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &create_data_object__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   create_texture_object__init
                     (CreateTextureObject         *message)
{
  static CreateTextureObject init_value = CREATE_TEXTURE_OBJECT__INIT;
  *message = init_value;
}
size_t create_texture_object__get_packed_size
                     (const CreateTextureObject *message)
{
  assert(message->base.descriptor == &create_texture_object__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t create_texture_object__pack
                     (const CreateTextureObject *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &create_texture_object__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t create_texture_object__pack_to_buffer
                     (const CreateTextureObject *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &create_texture_object__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CreateTextureObject *
       create_texture_object__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CreateTextureObject *)
     protobuf_c_message_unpack (&create_texture_object__descriptor,
                                allocator, len, data);
}
void   create_texture_object__free_unpacked
                     (CreateTextureObject *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &create_texture_object__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   set_render_buffer__init
                     (SetRenderBuffer         *message)
{
  static SetRenderBuffer init_value = SET_RENDER_BUFFER__INIT;
  *message = init_value;
}
size_t set_render_buffer__get_packed_size
                     (const SetRenderBuffer *message)
{
  assert(message->base.descriptor == &set_render_buffer__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t set_render_buffer__pack
                     (const SetRenderBuffer *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &set_render_buffer__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t set_render_buffer__pack_to_buffer
                     (const SetRenderBuffer *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &set_render_buffer__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SetRenderBuffer *
       set_render_buffer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SetRenderBuffer *)
     protobuf_c_message_unpack (&set_render_buffer__descriptor,
                                allocator, len, data);
}
void   set_render_buffer__free_unpacked
                     (SetRenderBuffer *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &set_render_buffer__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   update_system_matrix__init
                     (UpdateSystemMatrix         *message)
{
  static UpdateSystemMatrix init_value = UPDATE_SYSTEM_MATRIX__INIT;
  *message = init_value;
}
size_t update_system_matrix__get_packed_size
                     (const UpdateSystemMatrix *message)
{
  assert(message->base.descriptor == &update_system_matrix__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t update_system_matrix__pack
                     (const UpdateSystemMatrix *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &update_system_matrix__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t update_system_matrix__pack_to_buffer
                     (const UpdateSystemMatrix *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &update_system_matrix__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UpdateSystemMatrix *
       update_system_matrix__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UpdateSystemMatrix *)
     protobuf_c_message_unpack (&update_system_matrix__descriptor,
                                allocator, len, data);
}
void   update_system_matrix__free_unpacked
                     (UpdateSystemMatrix *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &update_system_matrix__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   destroy_data_object__init
                     (DestroyDataObject         *message)
{
  static DestroyDataObject init_value = DESTROY_DATA_OBJECT__INIT;
  *message = init_value;
}
size_t destroy_data_object__get_packed_size
                     (const DestroyDataObject *message)
{
  assert(message->base.descriptor == &destroy_data_object__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t destroy_data_object__pack
                     (const DestroyDataObject *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &destroy_data_object__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t destroy_data_object__pack_to_buffer
                     (const DestroyDataObject *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &destroy_data_object__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DestroyDataObject *
       destroy_data_object__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DestroyDataObject *)
     protobuf_c_message_unpack (&destroy_data_object__descriptor,
                                allocator, len, data);
}
void   destroy_data_object__free_unpacked
                     (DestroyDataObject *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &destroy_data_object__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   create_geometry_object__init
                     (CreateGeometryObject         *message)
{
  static CreateGeometryObject init_value = CREATE_GEOMETRY_OBJECT__INIT;
  *message = init_value;
}
size_t create_geometry_object__get_packed_size
                     (const CreateGeometryObject *message)
{
  assert(message->base.descriptor == &create_geometry_object__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t create_geometry_object__pack
                     (const CreateGeometryObject *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &create_geometry_object__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t create_geometry_object__pack_to_buffer
                     (const CreateGeometryObject *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &create_geometry_object__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CreateGeometryObject *
       create_geometry_object__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CreateGeometryObject *)
     protobuf_c_message_unpack (&create_geometry_object__descriptor,
                                allocator, len, data);
}
void   create_geometry_object__free_unpacked
                     (CreateGeometryObject *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &create_geometry_object__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   create_mesh_color__init
                     (CreateMeshColor         *message)
{
  static CreateMeshColor init_value = CREATE_MESH_COLOR__INIT;
  *message = init_value;
}
size_t create_mesh_color__get_packed_size
                     (const CreateMeshColor *message)
{
  assert(message->base.descriptor == &create_mesh_color__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t create_mesh_color__pack
                     (const CreateMeshColor *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &create_mesh_color__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t create_mesh_color__pack_to_buffer
                     (const CreateMeshColor *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &create_mesh_color__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CreateMeshColor *
       create_mesh_color__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CreateMeshColor *)
     protobuf_c_message_unpack (&create_mesh_color__descriptor,
                                allocator, len, data);
}
void   create_mesh_color__free_unpacked
                     (CreateMeshColor *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &create_mesh_color__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   create_mesh_texture__init
                     (CreateMeshTexture         *message)
{
  static CreateMeshTexture init_value = CREATE_MESH_TEXTURE__INIT;
  *message = init_value;
}
size_t create_mesh_texture__get_packed_size
                     (const CreateMeshTexture *message)
{
  assert(message->base.descriptor == &create_mesh_texture__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t create_mesh_texture__pack
                     (const CreateMeshTexture *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &create_mesh_texture__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t create_mesh_texture__pack_to_buffer
                     (const CreateMeshTexture *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &create_mesh_texture__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CreateMeshTexture *
       create_mesh_texture__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CreateMeshTexture *)
     protobuf_c_message_unpack (&create_mesh_texture__descriptor,
                                allocator, len, data);
}
void   create_mesh_texture__free_unpacked
                     (CreateMeshTexture *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &create_mesh_texture__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor reply__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Reply, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error_code",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Reply, error_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned reply__field_indices_by_name[] = {
  1,   /* field[1] = error_code */
  0,   /* field[0] = id */
};
static const ProtobufCIntRange reply__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor reply__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Reply",
  "Reply",
  "Reply",
  "",
  sizeof(Reply),
  2,
  reply__field_descriptors,
  reply__field_indices_by_name,
  1,  reply__number_ranges,
  (ProtobufCMessageInit) reply__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor create_scene__field_descriptors[1] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CreateScene, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned create_scene__field_indices_by_name[] = {
  0,   /* field[0] = name */
};
static const ProtobufCIntRange create_scene__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor create_scene__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CreateScene",
  "CreateScene",
  "CreateScene",
  "",
  sizeof(CreateScene),
  1,
  create_scene__field_descriptors,
  create_scene__field_indices_by_name,
  1,  create_scene__number_ranges,
  (ProtobufCMessageInit) create_scene__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor destroy_scene__field_descriptors[1] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DestroyScene, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned destroy_scene__field_indices_by_name[] = {
  0,   /* field[0] = id */
};
static const ProtobufCIntRange destroy_scene__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor destroy_scene__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DestroyScene",
  "DestroyScene",
  "DestroyScene",
  "",
  sizeof(DestroyScene),
  1,
  destroy_scene__field_descriptors,
  destroy_scene__field_indices_by_name,
  1,  destroy_scene__number_ranges,
  (ProtobufCMessageInit) destroy_scene__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor create_memory__field_descriptors[2] =
{
  {
    "scene_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateMemory, scene_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateMemory, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned create_memory__field_indices_by_name[] = {
  0,   /* field[0] = scene_id */
  1,   /* field[1] = size */
};
static const ProtobufCIntRange create_memory__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor create_memory__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CreateMemory",
  "CreateMemory",
  "CreateMemory",
  "",
  sizeof(CreateMemory),
  2,
  create_memory__field_descriptors,
  create_memory__field_indices_by_name,
  1,  create_memory__number_ranges,
  (ProtobufCMessageInit) create_memory__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue create_data_object__type__enum_values_by_number[6] =
{
  { "UV", "CREATE_DATA_OBJECT__TYPE__UV", 0 },
  { "COLOR", "CREATE_DATA_OBJECT__TYPE__COLOR", 1 },
  { "VERTEX", "CREATE_DATA_OBJECT__TYPE__VERTEX", 2 },
  { "NORMAL", "CREATE_DATA_OBJECT__TYPE__NORMAL", 3 },
  { "INDEX", "CREATE_DATA_OBJECT__TYPE__INDEX", 4 },
  { "MATRIX", "CREATE_DATA_OBJECT__TYPE__MATRIX", 5 },
};
static const ProtobufCIntRange create_data_object__type__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex create_data_object__type__enum_values_by_name[6] =
{
  { "COLOR", 1 },
  { "INDEX", 4 },
  { "MATRIX", 5 },
  { "NORMAL", 3 },
  { "UV", 0 },
  { "VERTEX", 2 },
};
const ProtobufCEnumDescriptor create_data_object__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "CreateDataObject.Type",
  "Type",
  "CreateDataObject__Type",
  "",
  6,
  create_data_object__type__enum_values_by_number,
  6,
  create_data_object__type__enum_values_by_name,
  1,
  create_data_object__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor create_data_object__field_descriptors[7] =
{
  {
    "scene_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateDataObject, scene_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "memory_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateDataObject, memory_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(CreateDataObject, type),
    &create_data_object__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "offset",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateDataObject, offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateDataObject, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nr_strides",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateDataObject, nr_strides),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stride",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateDataObject, stride),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned create_data_object__field_indices_by_name[] = {
  1,   /* field[1] = memory_id */
  5,   /* field[5] = nr_strides */
  3,   /* field[3] = offset */
  0,   /* field[0] = scene_id */
  4,   /* field[4] = size */
  6,   /* field[6] = stride */
  2,   /* field[2] = type */
};
static const ProtobufCIntRange create_data_object__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor create_data_object__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CreateDataObject",
  "CreateDataObject",
  "CreateDataObject",
  "",
  sizeof(CreateDataObject),
  7,
  create_data_object__field_descriptors,
  create_data_object__field_indices_by_name,
  1,  create_data_object__number_ranges,
  (ProtobufCMessageInit) create_data_object__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue create_texture_object__format__enum_values_by_number[1] =
{
  { "RGB8", "CREATE_TEXTURE_OBJECT__FORMAT__RGB8", 0 },
};
static const ProtobufCIntRange create_texture_object__format__value_ranges[] = {
{0, 0},{0, 1}
};
static const ProtobufCEnumValueIndex create_texture_object__format__enum_values_by_name[1] =
{
  { "RGB8", 0 },
};
const ProtobufCEnumDescriptor create_texture_object__format__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "CreateTextureObject.Format",
  "Format",
  "CreateTextureObject__Format",
  "",
  1,
  create_texture_object__format__enum_values_by_number,
  1,
  create_texture_object__format__enum_values_by_name,
  1,
  create_texture_object__format__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue create_texture_object__type__enum_values_by_number[2] =
{
  { "TEXTURE_2D", "CREATE_TEXTURE_OBJECT__TYPE__TEXTURE_2D", 0 },
  { "TEXTURE_CUBE_MAP", "CREATE_TEXTURE_OBJECT__TYPE__TEXTURE_CUBE_MAP", 1 },
};
static const ProtobufCIntRange create_texture_object__type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex create_texture_object__type__enum_values_by_name[2] =
{
  { "TEXTURE_2D", 0 },
  { "TEXTURE_CUBE_MAP", 1 },
};
const ProtobufCEnumDescriptor create_texture_object__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "CreateTextureObject.Type",
  "Type",
  "CreateTextureObject__Type",
  "",
  2,
  create_texture_object__type__enum_values_by_number,
  2,
  create_texture_object__type__enum_values_by_name,
  1,
  create_texture_object__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor create_texture_object__field_descriptors[8] =
{
  {
    "scene_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateTextureObject, scene_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "memory_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateTextureObject, memory_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "offset",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateTextureObject, offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateTextureObject, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "width",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateTextureObject, width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "height",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateTextureObject, height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "format",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(CreateTextureObject, format),
    &create_texture_object__format__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(CreateTextureObject, type),
    &create_texture_object__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned create_texture_object__field_indices_by_name[] = {
  6,   /* field[6] = format */
  5,   /* field[5] = height */
  1,   /* field[1] = memory_id */
  2,   /* field[2] = offset */
  0,   /* field[0] = scene_id */
  3,   /* field[3] = size */
  7,   /* field[7] = type */
  4,   /* field[4] = width */
};
static const ProtobufCIntRange create_texture_object__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor create_texture_object__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CreateTextureObject",
  "CreateTextureObject",
  "CreateTextureObject",
  "",
  sizeof(CreateTextureObject),
  8,
  create_texture_object__field_descriptors,
  create_texture_object__field_indices_by_name,
  1,  create_texture_object__number_ranges,
  (ProtobufCMessageInit) create_texture_object__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor set_render_buffer__field_descriptors[3] =
{
  {
    "scene_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SetRenderBuffer, scene_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "memory_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SetRenderBuffer, memory_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nr_objects",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SetRenderBuffer, nr_objects),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned set_render_buffer__field_indices_by_name[] = {
  1,   /* field[1] = memory_id */
  2,   /* field[2] = nr_objects */
  0,   /* field[0] = scene_id */
};
static const ProtobufCIntRange set_render_buffer__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor set_render_buffer__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SetRenderBuffer",
  "SetRenderBuffer",
  "SetRenderBuffer",
  "",
  sizeof(SetRenderBuffer),
  3,
  set_render_buffer__field_descriptors,
  set_render_buffer__field_indices_by_name,
  1,  set_render_buffer__number_ranges,
  (ProtobufCMessageInit) set_render_buffer__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue update_system_matrix__matrix_type__enum_values_by_number[2] =
{
  { "HEAD", "UPDATE_SYSTEM_MATRIX__MATRIX_TYPE__HEAD", 0 },
  { "BODY", "UPDATE_SYSTEM_MATRIX__MATRIX_TYPE__BODY", 1 },
};
static const ProtobufCIntRange update_system_matrix__matrix_type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex update_system_matrix__matrix_type__enum_values_by_name[2] =
{
  { "BODY", 1 },
  { "HEAD", 0 },
};
const ProtobufCEnumDescriptor update_system_matrix__matrix_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "UpdateSystemMatrix.MatrixType",
  "MatrixType",
  "UpdateSystemMatrix__MatrixType",
  "",
  2,
  update_system_matrix__matrix_type__enum_values_by_number,
  2,
  update_system_matrix__matrix_type__enum_values_by_name,
  1,
  update_system_matrix__matrix_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue update_system_matrix__update_type__enum_values_by_number[2] =
{
  { "MULTIPLY", "UPDATE_SYSTEM_MATRIX__UPDATE_TYPE__MULTIPLY", 0 },
  { "SET", "UPDATE_SYSTEM_MATRIX__UPDATE_TYPE__SET", 1 },
};
static const ProtobufCIntRange update_system_matrix__update_type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex update_system_matrix__update_type__enum_values_by_name[2] =
{
  { "MULTIPLY", 0 },
  { "SET", 1 },
};
const ProtobufCEnumDescriptor update_system_matrix__update_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "UpdateSystemMatrix.UpdateType",
  "UpdateType",
  "UpdateSystemMatrix__UpdateType",
  "",
  2,
  update_system_matrix__update_type__enum_values_by_number,
  2,
  update_system_matrix__update_type__enum_values_by_name,
  1,
  update_system_matrix__update_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor update_system_matrix__field_descriptors[6] =
{
  {
    "scene_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(UpdateSystemMatrix, scene_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "memory_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(UpdateSystemMatrix, memory_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "matrix_type",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(UpdateSystemMatrix, matrix_type),
    &update_system_matrix__matrix_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "update_type",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(UpdateSystemMatrix, update_type),
    &update_system_matrix__update_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "offset",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(UpdateSystemMatrix, offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(UpdateSystemMatrix, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned update_system_matrix__field_indices_by_name[] = {
  2,   /* field[2] = matrix_type */
  1,   /* field[1] = memory_id */
  4,   /* field[4] = offset */
  0,   /* field[0] = scene_id */
  5,   /* field[5] = size */
  3,   /* field[3] = update_type */
};
static const ProtobufCIntRange update_system_matrix__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor update_system_matrix__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "UpdateSystemMatrix",
  "UpdateSystemMatrix",
  "UpdateSystemMatrix",
  "",
  sizeof(UpdateSystemMatrix),
  6,
  update_system_matrix__field_descriptors,
  update_system_matrix__field_indices_by_name,
  1,  update_system_matrix__number_ranges,
  (ProtobufCMessageInit) update_system_matrix__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor destroy_data_object__field_descriptors[2] =
{
  {
    "scene_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DestroyDataObject, scene_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(DestroyDataObject, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned destroy_data_object__field_indices_by_name[] = {
  1,   /* field[1] = id */
  0,   /* field[0] = scene_id */
};
static const ProtobufCIntRange destroy_data_object__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor destroy_data_object__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DestroyDataObject",
  "DestroyDataObject",
  "DestroyDataObject",
  "",
  sizeof(DestroyDataObject),
  2,
  destroy_data_object__field_descriptors,
  destroy_data_object__field_indices_by_name,
  1,  destroy_data_object__number_ranges,
  (ProtobufCMessageInit) destroy_data_object__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor create_geometry_object__field_descriptors[4] =
{
  {
    "scene_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateGeometryObject, scene_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vertex_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateGeometryObject, vertex_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "normal_id",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateGeometryObject, normal_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "index_id",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateGeometryObject, index_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned create_geometry_object__field_indices_by_name[] = {
  3,   /* field[3] = index_id */
  2,   /* field[2] = normal_id */
  0,   /* field[0] = scene_id */
  1,   /* field[1] = vertex_id */
};
static const ProtobufCIntRange create_geometry_object__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor create_geometry_object__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CreateGeometryObject",
  "CreateGeometryObject",
  "CreateGeometryObject",
  "",
  sizeof(CreateGeometryObject),
  4,
  create_geometry_object__field_descriptors,
  create_geometry_object__field_indices_by_name,
  1,  create_geometry_object__number_ranges,
  (ProtobufCMessageInit) create_geometry_object__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor create_mesh_color__field_descriptors[6] =
{
  {
    "scene_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateMeshColor, scene_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "geometry_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateMeshColor, geometry_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(CreateMeshColor, r),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "g",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(CreateMeshColor, g),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "b",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(CreateMeshColor, b),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "a",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(CreateMeshColor, a),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned create_mesh_color__field_indices_by_name[] = {
  5,   /* field[5] = a */
  4,   /* field[4] = b */
  3,   /* field[3] = g */
  1,   /* field[1] = geometry_id */
  2,   /* field[2] = r */
  0,   /* field[0] = scene_id */
};
static const ProtobufCIntRange create_mesh_color__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor create_mesh_color__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CreateMeshColor",
  "CreateMeshColor",
  "CreateMeshColor",
  "",
  sizeof(CreateMeshColor),
  6,
  create_mesh_color__field_descriptors,
  create_mesh_color__field_indices_by_name,
  1,  create_mesh_color__number_ranges,
  (ProtobufCMessageInit) create_mesh_color__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor create_mesh_texture__field_descriptors[4] =
{
  {
    "scene_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateMeshTexture, scene_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "geometry_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateMeshTexture, geometry_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "texture_id",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateMeshTexture, texture_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uv_id",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreateMeshTexture, uv_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned create_mesh_texture__field_indices_by_name[] = {
  1,   /* field[1] = geometry_id */
  0,   /* field[0] = scene_id */
  2,   /* field[2] = texture_id */
  3,   /* field[3] = uv_id */
};
static const ProtobufCIntRange create_mesh_texture__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor create_mesh_texture__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CreateMeshTexture",
  "CreateMeshTexture",
  "CreateMeshTexture",
  "",
  sizeof(CreateMeshTexture),
  4,
  create_mesh_texture__field_descriptors,
  create_mesh_texture__field_indices_by_name,
  1,  create_mesh_texture__number_ranges,
  (ProtobufCMessageInit) create_mesh_texture__init,
  NULL,NULL,NULL    /* reserved[123] */
};
